default_language_version:
    python: python3.8
fail_fast: false
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: end-of-file-fixer
    -   id: check-builtin-literals
    -   id: check-ast
    -   id: check-json
    -   id: detect-private-key
    -   id: requirements-txt-fixer

-   repo: https://github.com/psf/black
    rev: '24.2.0'
    hooks:
      - id: black

-   repo: https://github.com/pycqa/isort
    rev: '5.13.2'
    hooks:
      - id: isort

        args: [--profile=black]

-   repo: local
    hooks:
      - id: readmegen
        name: readmegen
        description: >-
          Script to automatically generate readme.md
        entry: python ./.utils/utils.py makereadme
        language: python
        additional_dependencies:
          - babel~=2.9.0
          - tabulate~=0.8.9
          - click
        always_run: true
        pass_filenames: false
        require_serial: true
        verbose: true

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks.
  autofix_prs: true
  autoupdate_branch: "master"
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: weekly
  skip: []
  submodules: false
